name: SCP Files Action
author: Adam Wasilewski
description: Secure copy files from repo to remote server

inputs:
  host:
    description: Remote host
    required: true
  port:
    description: Remote host SSH port
    required: true
    default: 22
  user:
    description: Remote host user
    required: true
  key:
    description: SSH private key
    required: true
  source:
    description: Repo directory path. Default whole repo
    required: true
    default: "$(pwd)/"
  destination:
    description: Remote directory path. Default home directory
    required: true
    default: "~/"

runs:
  using: docker
  image: Dockerfile

branding:
  icon: "upload-cloud"
  color: "gray-dark"
